const Razorpay = require('razorpay');
const crypto = require('crypto'); // Built-in Node.js module for signature verification

// --- 1. INITIALIZE RAZORPAY INSTANCE ---
// Credentials are loaded from the .env file
const razorpayInstance = new Razorpay({
    key_id: process.env.RAZORPAY_KEY_ID,     // <-- REPLACE IN .ENV
    key_secret: process.env.RAZORPAY_KEY_SECRET, // <-- REPLACE IN .ENV
});

/**
 * Creates a Razorpay order ID.
 * This ID is sent to the frontend to initialize the payment popup.
 * @param {number} amountInPaisa - The total amount in the smallest currency unit (e.g., 50000 for ₹500.00)
 * @param {string} currency - Currency code (e.g., "INR")
 * @returns {Promise<object>} - The Razorpay order object (or throws an error)
 */
const createRazorpayOrder = async (amountInPaisa, currency = "INR") => {
    const options = {
        amount: amountInPaisa,
        currency: currency,
        receipt: `receipt_order_${new Date().getTime()}`, // A unique receipt ID
    };

    try {
        // Use the instance to create an order
        const order = await razorpayInstance.orders.create(options);
        
        if (!order) {
            throw new Error('Razorpay order creation failed');
        }
        
        return order; // Returns { id, entity, amount, currency, status, ... }
        
    } catch (error) {
        console.error("Razorpay Service Error:", error);
        throw new Error('Failed to create Razorpay order');
    }
};

/**
 * Verifies the Razorpay payment signature.
 * This is crucial for confirming the payment is authentic and successful.
 * @param {string} razorpay_order_id - The order ID from Razorpay
 * @param {string} razorpay_payment_id - The payment ID from Razorpay
 * @param {string} razorpay_signature - The signature sent by Razorpay webhook/callback
 * @returns {boolean} - True if the signature is valid, false otherwise
 */
const verifyRazorpaySignature = (razorpay_order_id, razorpay_payment_id, razorpay_signature) => {
    
    // The secret key from your .env file
    const secret = process.env.RAZORPAY_KEY_SECRET;

    // --- 1. CREATE THE HASH ---
    // The signature is generated by hashing the order_id + "|" + payment_id
    const generated_signature = crypto
        .createHmac('sha256', secret)
        .update(razorpay_order_id + "|" + razorpay_payment_id)
        .digest('hex');

    // --- 2. COMPARE HASHES ---
    // This is a timing-safe comparison to prevent timing attacks
    const isSignatureValid = crypto.timingSafeEqual(
        Buffer.from(generated_signature),
        Buffer.from(razorpay_signature)
    );

    return isSignatureValid;
};


module.exports = {
    razorpayInstance,
    createRazorpayOrder,
    verifyRazorpaySignature,
};